///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: img/music/ingameSong_1.aks
/// Generation time: vie oct 25 11:55:32 CEST 2019
///

/// Song 'song_ingame2' metadata macros
#define song_ingame2_address  0x0285
#define song_ingame2_size     162
#define song_ingame2_end      0x326

/// Song 'song_ingame2' array declaration
extern void song_ingame2[song_ingame2_size];
