///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: img/music/instrumentos.aks
/// Generation time: vie oct 25 13:24:55 CEST 2019
///

/// Song 'sfx_instrumentos' metadata macros
#define sfx_instrumentos_address  0x0974
#define sfx_instrumentos_size     290
#define sfx_instrumentos_end      0xa95

/// Song 'sfx_instrumentos' array declaration
extern void sfx_instrumentos[sfx_instrumentos_size];
