///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: img/music/mainMenuSong.aks
/// Generation time: vie oct 25 11:55:33 CEST 2019
///

/// Song 'song_ingame1' metadata macros
#define song_ingame1_address  0x0162
#define song_ingame1_size     291
#define song_ingame1_end      0x284

/// Song 'song_ingame1' array declaration
extern void song_ingame1[song_ingame1_size];
