///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: img/music/mainMenuSong.aks
/// Generation time: vie oct 25 13:24:54 CEST 2019
///

/// Song 'song_ingame1' metadata macros
#define song_ingame1_address  0x0A96
#define song_ingame1_size     291
#define song_ingame1_end      0xbb8

/// Song 'song_ingame1' array declaration
extern void song_ingame1[song_ingame1_size];
