///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: img/music/molusk.aks
/// Generation time: lun oct 21 17:14:34 CEST 2019
///

/// Song 'song_ingame1' metadata macros
#define song_ingame1_address  0x0040
#define song_ingame1_size     8883
#define song_ingame1_end      0x22f2

/// Song 'song_ingame1' array declaration
extern void song_ingame1[song_ingame1_size];
