///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: img/music/prueba1.aks
/// Generation time: lun oct 21 17:14:33 CEST 2019
///

/// Song 'song_ingame2' metadata macros
#define song_ingame2_address  0x22f3
#define song_ingame2_size     124
#define song_ingame2_end      0x236e

/// Song 'song_ingame2' array declaration
extern void song_ingame2[song_ingame2_size];
