// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _tilemap_pal_H_
#define _tilemap_pal_H_

#include <types.h>

extern const u8 tilemap_pal[16];

#endif
